# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeda974ada08a1339e5af3997128f98ee16b3be1b24a35aa104c16cc45f296adbc9d28271aac145198c0ca9ec763a9363bfae32c809947de8fd4900d25e5b8af

test:
  secret_key_base: 71f7f20f92879b42bc929f194e243323737ea29642b928f81f23b99da2509454cb3d5309befec0c7951f143001ae481693f72c323b10257fd4a1e0631f92c381

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
